# This workflow is for deploying the backend project 'db' in my Oracle cloud vm.
# This workflow should access the vm via ssh, and run command git pull to update the code, and then run command 'pnpm install' to install the dependencies of this monorepo.
# And I want to run `sudo systemctl restart usealarmbackend` to restart the service.

name: Backend Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd /home/ubuntu/alarm-repo            
            git pull
            ${{ secrets.REMOTE_GIT_PASSWORD }}
            nvm use 22
            pnpm install
            sudo systemctl restart usealarmbackend

# Can I enter the password of github ssh before pulling?
# I want to enter the password of github ssh before pulling.
# I want to enter the password of github ssh before pulling.
# I want to enter the password of github ssh before pulling.
# I want to enter the password of github ssh before pulling.
# I want to enter the password of github ssh before pulling.
# I want to enter the password of github ssh before pulling.

