name: Backend Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd /home/ubuntu
            echo 'echo ${{ secrets.REMOTE_SSH_USERNAME }}' > ~/.ssh/passphrase && chmod 700 ~/.ssh/passphrase
            eval `ssh-agent -s`
            DISPLAY=None SSH_ASKPASS=~/.ssh/passphrase ssh-add /home/ubuntu/.ssh/id_ed25519
            cd /home/ubuntu/alarm-repo   
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh         
            sudo git pull
            nvm use 22
            pnpm install
            sudo systemctl restart usealarmbackend
