name: Backend Deploy

on:
  push:
    branches: [main]
    paths:
      - "!web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu
            echo 'echo ${{ secrets.REMOTE_GIT_PASSWORD }}' > ~/.ssh/passphrase.sh && chmod a+x ~/.ssh/passphrase.sh
            eval `ssh-agent -s`
            DISPLAY=1 SSH_ASKPASS=~/.ssh/passphrase.sh SSH_ASKPASS_REQUIRE=force ssh-add /home/ubuntu/.ssh/id_ed25519
            cd /home/ubuntu/alarm-repo   
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh         
            git pull
            nvm use 22
            pnpm install
            sudo systemctl restart usealarmbackend
            cd /home/ubuntu/alarm-repo/notification && pnpm tsc
            pm2 restart alarm-notification
            rm ~/.ssh/passphrase.sh
