name: Backend Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd /home/ubuntu/alarm-repo            
            git pull
            ${{ secrets.REMOTE_GIT_PASSWORD }}
            nvm use 22
            pnpm install
            sudo systemctl restart usealarmbackend
